.TH "BAMBOOSTER" "1" "May 2020" "Bambooster" ""

.SH NAME
Bambooster \- a BitTorrent client in C++ with Qt5

.SH SYNOPSIS

\fBBambooster\fR
.PP
.SH "DESCRIPTION"

\fBqTorrent\fR is a simple BitTorrent client, written from scratch in C++ with Qt5.
qTorrent aims to be a good, lightweight alternative to all the other BitTorrent clients.
.br
It provides the minimal features required for a standard BitTorrent client.
.PP
.SH "AUTHOR"

Maksim Bambiza <MiJlbliiii@gmail.com>
